const Map<String, String> en = {
  "name_app": "MyApp",
  "error_wrong": "Something went wrong try again later",
  "name": "Name",
  "pin": "PIN",
  "trial_period_end": "Your trial period will end on %s",
  "oops": "Oops!",
  "password": "Password",
  "required_field": "field is required",
  "forgot_pass": "forgot password?",
  "forgot_password": "Forgot Password",
  "error_login": "name or password is incorrect",
  "error_server": "error connecting to server please try again",
  "success_login": "login successful",
  "completed_success": "Completed successfully",
  "signin": "Sign in",
  "signup": "Sign up",
  "contacts": "Contacts",
  "profile": "Profile",
  "logout": "Logout",
  "exit_app": "Are you sure you want to Exit?",
  "get_started": "Get Started",
  "no": "No",
  "yes": "Yes",
};
